### ISSUE TITLE
Pod goes to CrashLoopBackOff when attached pv created using mapr-csi

### ISSUE THREAD

**Issue by nallurichandu99** [mapr/mapr-csi#14] opened 2019-06-26 18:35 UTC
---
**What happened:**
I have a mapr cluster with kubernetes running on top of it.  Deployed mapr-csi driver as per the official documentation. Plan is to create pv's dynamically using a storage class. The mapr user has access to the apiserver and can create and remove volumes. Once everyting is deployed  tested with a sample busybox deployment with PersistentVolumeClaim which deployed a volume and can write into the pv.

After the sample deploymets tried deploying the helm charts for mysql and postgresql which started going to `CrashLoopBackOff`. Pod logs show the configuration files can't be written and found the following logs from `/var/log/csi-maprkdf/d1e5b0a6-9760-11e9-8cad-005056a613b2-mapr-pv-07d44d4e-96dc-11e9-bceb-005056a625fc`
Not seeing any error logs in csi-plugin or kubelet

**Anything else we need to know?:**
The pod comes up fine without persistence enabled or if we change the mount path to some other which is different from the actual mount path where the container writes the required files.
Users in the container are mysql for mysql deployment and postgres for postgresql deployment.

**Error Logs:**
![Screen Shot 2019-06-25 at 11 30 10 AM](https://user-images.githubusercontent.com/44781363/60197081-54b5c300-9804-11e9-8387-7b2357285d27.png)

`[root@xxxxx csi-maprkdf]# cat d1e5b0a6-9760-11e9-8cad-005056a613b2-mapr-pv-07d44d4e-96dc-11e9-bceb-005056a625fc/ffs.log-0
2019-06-25 10:49:41,4770 ERROR FuseAPI fc/fuse_api.cc:1389 Thread: 685 Shmid to be used by fcdebug 851979, guts 0
2019-06-25 10:49:48,5582 ERROR Client fc/client.cc:10024 Thread: 701 <DoWriteRPC: write resp for file 3005.53.136350, error 22, fid 3015.33.131242, primary fid 3005.53.136350, node 10.208.45.156:5692, off 65536,, count 524288
2019-06-25 10:49:48,5582 ERROR Client fc/writebuf.cc:560 Thread: 701 FlushWrite failed: File 3005.53.136350, error: Invalid argument(22), pfid 3005.53.136350, off 65536, fid 3015.33.131242
2019-06-25 10:49:48,5582 ERROR Client fc/writequeue.cc :153 Thread: 701 WriteBuf null/err. 22
2019-06-25 10:49:48,5583 ERROR Client fc/writequeue.cc :153 Thread: 703 WriteBuf null/err. 22
2019-06-25 10:49:48,5583 ERROR LibHdfsApiSupport fc/libhdfs/fuse_support.cc:447 Thread: 748 write failed, file 3005.53.136350, error: 22
2019-06-25 10:49:48,5583 ERROR FuseOps fs/client/fuse/cc/fuse_ops_ll.c:3271 Thread: 748 write: ino 806648545333 offset 917504 size 131072 error -22
2019-06-25 10:49:48,5583 ERROR FuseOps fs/client/fuse/cc/fuse_ops_ll.c:3358 Thread: 748 write_buf: failed, ino 806648545333 offset 917504 error 22
2019-06-25 10:49:48,5586 ERROR LibHdfsApiSupport fc/libhdfs/fuse_support.cc:447 Thread: 749 write failed, file 3005.53.136350, error: 22
2019-06-25 10:49:48,5586 ERROR FuseOps fs/client/fuse/cc/fuse_ops_ll.c:3271 Thread: 749 write: ino 806648545333 offset 917504 size 131072 error -22
2019-06-25 10:49:48,5586 ERROR FuseOps fs/client/fuse/cc/fuse_ops_ll.c:3358 Thread: 749 write_buf: failed, ino 806648545333 offset 917504 error 22
2019-06-25 10:49:49,1594 ERROR FuseOps fs/client/fuse/cc/fuse_ops_ll.c:2478 Thread: 750 flush_shard_helper: failed, ino 806648545333 err 22
2019-06-25 10:49:49,1594 ERROR FuseOps fs/client/fuse/cc/fuse_ops_ll.c:2520 Thread: 750 mfuse_flush_shard_ll: failed, ino 806648545333 error 22
2019-06-25 10:49:49,1602 ERROR Fusell fs/client/fuse/cc/fuse_ll.c:1453 Thread: 751 release: failed, ino 806648545333, error -1
2019-06-25 15:27:10,3796 ERROR Client fc/client.cc:9470 Thread: 714 Read failed for file 3005.53.136350, error Invalid argument(22), off 0 len 16384 for fid 3005.53.136350
2019-06-25 15:27:10,3796 ERROR LibHdfsApiSupport fc/libhdfs/fuse_support.cc:188 Thread: 714 Read failed for file 3005.53.136350, startOff 0 length 16384, error -22
2019-06-25 15:27:10,3796 ERROR Fusell fs/client/fuse/cc/fuse_ll.c:1338 Thread: 714 read: failed, ino 806648545333 offset 0 count 16384 error 22
2019-06-25 15:27:10,3796 ERROR Fusell fs/client/fuse/cc/fuse_ll.c:1398 Thread: 714 mfuse_read_shard_ll: failed, ino 806648545333 offset 0 size 16384 error 22
2019-06-25 15:27:10,3802 ERROR Client fc/client.cc:9470 Thread: 713 Read failed for file 3005.53.136350, error Invalid argument(22), off 0 len 4096 for fid 3005.53.136350
2019-06-25 15:27:10,3802 ERROR LibHdfsApiSupport fc/libhdfs/fuse_support.cc:188 Thread: 713 Read failed for file 3005.53.136350, startOff 0 length 4096, error -22
2019-06-25 15:27:10,3802 ERROR Fusell fs/client/fuse/cc/fuse_ll.c:1338 Thread: 713 read: failed, ino 806648545333 offset 0 count 4096 error 22
2019-06-25 15:27:10,3802 ERROR Fusell fs/client/fuse/cc/fuse_ll.c:1398 Thread: 713 mfuse_read_shard_ll: failed, ino 806648545333 offset 0 size 4096 error 22
2019-06-26 03:33:07,4992 ERROR Client fc/client.cc:9470 Thread: 713 Read failed for file 3005.53.136350, error Invalid argument(22), off 0 len 16384 for fid 3005.53.136350
2019-06-26 03:33:07,5041 ERROR LibHdfsApiSupport fc/libhdfs/fuse_support.cc:188 Thread: 713 Read failed for file 3005.53.136350, startOff 0 length 16384, error -22
2019-06-26 03:33:07,5041 ERROR Fusell fs/client/fuse/cc/fuse_ll.c:1338 Thread: 713 read: failed, ino 806648545333 offset 0 count 16384 error 22
2019-06-26 03:33:07,5041 ERROR Fusell fs/client/fuse/cc/fuse_ll.c:1398 Thread: 713 mfuse_read_shard_ll: failed, ino 806648545333 offset 0 size 16384 error 22
2019-06-26 03:33:07,5046 ERROR Client fc/client.cc:9470 Thread: 716 Read failed for file 3005.53.136350, error Invalid argument(22), off 0 len 4096 for fid 3005.53.136350
2019-06-26 03:33:07,5046 ERROR LibHdfsApiSupport fc/libhdfs/fuse_support.cc:188 Thread: 716 Read failed for file 3005.53.136350, startOff 0 length 4096, error -22
2019-06-26 03:33:07,5046 ERROR Fusell fs/client/fuse/cc/fuse_ll.c:1338 Thread: 716 read: failed, ino 806648545333 offset 0 count 4096 error 22
2019-06-26 03:33:07,5046 ERROR Fusell fs/client/fuse/cc/fuse_ll.c:1398 Thread: 716 mfuse_read_shard_ll: failed, ino 806648545333 offset 0 size 4096 error 22`

**Environment:**

- Kubernetes version (use kubectl version): 1.14.3
- MapRBuildVersion: 6.1.0.20180926230239.GA
- MapR MEP Version: 6.0.0
- Mapr Cluster Security: Unsecure
---

**Comment by sarjeet2013** [comment] 2019-06-30 20:36
@nallurichandu99 

> The MapR cluster is unsecure and both k8s and mapr are running on same cluster

I guess the problem is due to the `Unsecure cluster` behavior and this is working as expected. Let me try to explain it:

On Unsecure cluster, there is no way for the server to authorize the user writing/reading from the MapR FS volume as it requires the same user with same uid/gid to be present on the server (On MapR cluster) as well.

In your case, if you don't have `mysql/postgresuser` user on the server/cluster, server doesn't know if this user should have any access to read/write to the MapR volumes at all.

One way to solve this is to always match the user identity with same uid/gid/group from the client (container user) to the exact same user with uid/gid/group exists on the server and it should work then.

This issue shouldn't happen for Secure cluster as MapR SASL ticket becomes the source of truth and any user which can provide valid MapR ticket to CSI driver, then any container user is just reading/writing to MapR volume using the ticket identity and container user is just irrelevant in that case

Hope this helps

**Comment by rohanjayaraj** [comment] 2024-04-04 09:21
Closing issues older than a year.

**Closed as completed by rohanjayaraj** 2024-04-04 09:21 UTC
